### ISSUE TITLE
layout folder not included

### ISSUE THREAD

**Issue by nelsorco** [Open-Games-Community/Hellgrave-ZnoteAAC#2]
As title says, this folder is not included, you neither told if that was intended.
thanks in response.

**Comment by Alexv45** [comment]
> As title says, this folder is not included, you neither told if that was intended.
> thanks in response.

Hello,
As is writed on each website here,layout folder is not available for some reasons: big files, to much files, updates, etc.
You will find a link on each website redirecting to the forum thread where you will find the last website updated and you can download It.
